### ISSUE TITLE
Object has no method "watch"

### ISSUE THREAD

**Issue by destroytoday** [librato/statsd-librato-backend#46]
I'm really stumped by this one. I deployed my app after working only on the front-end, having not changed anything regarding statsd, but all of sudden this error appears and 503's my app:

```
4 Jan 02:55:13 - reading config file: config/statsd.js 
node.js:134 
        ^ 
started with pid 6 
 
        throw e; // process.nextTick error, or 'error' event on first tick 
TypeError: Object #<Object> has no method 'watch' 
    at new <anonymous> (/app/node_modules/statsd/lib/config.js:26:6) 
    at Object.configFile (/app/node_modules/statsd/lib/config.js:36:16) 
    at Object.<anonymous> (/app/node_modules/statsd/stats.js:146:8) 
    at Module._compile (module.js:404:26) 
    at Object..js (module.js:410:10) 
    at Module.load (module.js:336:31) 
    at Function._load (module.js:297:12) 
    at Array.<anonymous> (module.js:423:10) 
    at EventEmitter._tickCallback (node.js:126:26) 
exited with code 1 
sending SIGTERM to all processes 
```

Both statsd and statsd-librato-backend dependencies have been using the same versions since day one, and I haven't moved the config file. I'm running this using the multi-buildpack on Heroku.

I realize this error is coming from the statsd library, but wondered if you folks at Librato experienced anything similar recently. I'm really scratching my head here. Any ideas?

**Comment by destroytoday** [comment]
I just tried creating a separate heroku instance with the same dependencies and the error doesn't occur. Just my luck—I thought I'd be able to track it down. Any help would go a long way.

**Comment by mheffner** [comment]
@destroytoday Can't say I've seen this one. Are you still able to reproduce it?

**Comment by destroytoday** [comment]
Strangely, after updating the server to Ubuntu 14.04, it fixed itself... closing with a ¯\_(ツ)_/¯.
