### ISSUE TITLE
Log historical metrics through statsd

### ISSUE THREAD

**Issue by jeffandersen** [librato/statsd-librato-backend#51]
Librato metrics support supplying a `measure_time` property (not longer than 120mins old) on the payload.

Is there a mechanism within statsd that we can measure to also provide this value on a per-metric basis?

**Comment by mheffner** [comment]
@jeffandersen This would require changing statsd to support a timestamp parameter as part of the payload. This has been discussed before, but largely been dismissed: https://github.com/etsy/statsd/issues/279. Statsd is largely built for consuming, aggregating, and submitting high-volume, real-time samples, so supporting bucketing and aggregating values into certain time intervals would be a fairly large redesign.

Without knowing your specific use case, you may be better off looking at one of the Librato instrumentation libraries (eg. for Ruby, Java, Python, etc.) and use it to build a custom aggregation of the data over the historical time windows, then use it to submit those aggregations with the required measure_times.
