### ISSUE TITLE
Tag based logging is on by default

### ISSUE THREAD

**Issue by icha024** [librato/statsd-librato-backend#63]
Tag based logging is seem to be on by default in this library, but it didn't seem to be on by default in Librato. I'm currently seeing this error with the latest client and have to install the older version of this library to bypass this:

```27 Feb 14:38:56 - DEBUG: Sending Payload: {"time":1488206330,"tags":{"host":"my-machine-name.local"},"measurements":[{"name":"test.ian","value":2434,"tags":{"source":"preprod"}}]}
27 Feb 14:38:56 - LOG_ERR: Failed to post to Librato: HTTP 403: {"errors":["Tag based measurements are not enabled for this account. Contact support@librato.com for more information"]}```

**Comment by bryanmikaelian** [comment]
Hey @icha024! Thanks for bringing this up. As you said, this functionality is enabled by default but we forgot to make that clearer in our `README`. https://github.com/librato/statsd-librato-backend/pull/64 should make it clearer.

In the meantime, there is an undocumented flag `writeToLegacy` that you can use to enable the old way of submitting things to Librato. Once you are ready to start using tags, feel free to reach out to our support team!

**Comment by icha024** [comment]
@bryanmikaelian Thanks for the quick response.

I've reverted my code to using the latest v2.0.2 version and:
- Added `writeToLegacy` flag set to "true" in under librato config
- Manually edited `node_modules/statsd-librato-backend/lib/librato.js` to make sure it is set to true

I'm still seeing the error with tag based measurement in the console log when sending a test message `echo -n "test.ian:2634|g"  | nc -w 1 -u 127.0.0.1 8127`

**Comment by bryanmikaelian** [comment]
@icha024 Is your data showing up in Librato with `writeToLegacy` enabled?

As of right now, there is no way to suppress the error message since 2.x.x+ assumes tags are enabled for your account. You can downgrade to this [branch](https://github.com/librato/statsd-librato-backend/tree/branch-0.1.x) if the logged errors is causing issues.

**Comment by icha024** [comment]
@bryanmikaelian The data isn't showing up on Librato with `writeToLegacy: "true"` enabled. Also, the error logged seem to be repeating/retying itself every 10 seconds.

Sounds like we'll need to use the older branch for now until we get the tag enabled to try out the new clients.

**Comment by icha024** [comment]
Closing issue - Readme was updated and I got a solution :)

**Comment by bryanmikaelian** [comment]
Awesome. Glad you were able to figure out a solution!
