### ISSUE TITLE
Backend logging all by default

### ISSUE THREAD

**Issue by elblivion** [librato/statsd-librato-backend#87]
Hi,

We're deploying statsd in Kubernetes, and logging to stdout. We currently get everything in our logs, including "DEBUG" messages, e.g. https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L64-L66. 

Our config does not set the `debug` value in statsd, it seems something is forcing this `logAll` to be true - could you please help us out?

Thanks!

```
{
  librato: {
    email: process.env.LIBRATO_EMAIL,
    token: process.env.LIBRATO_TOKEN,
    host: false,
    tags: {
      cluster: process.env.CLUSTER_NAME,
      environment: process.env.CLUSTER_ENVIRONMENT
    }
  },
  backends: ['statsd-librato-backend'],
  percentThreshold: [95, 99],
  port: 8125,
  deleteIdleStats: true,
  keyNameSanitize: false
}
```

**Comment by bryanmikaelian** [comment]
Hmm... I know `logAll` will get set to `true` if no logger is set when the backend is initialized. Could that be what you are seeing? https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L467-L471

**Comment by elblivion** [comment]
I'm not really proficient in Javascript, but that seems to be the case. What should we do if we want to *not* `logAll`?

**Comment by bryanmikaelian** [comment]
It seems like we should honor `config.debug`, regardless if you have a statsd logger configured or not. The alternative is to remove your logger from your statsd instance which...isn't ideal.

I'll get a PR opened to fix this.

**Comment by elblivion** [comment]
Thanks!
